version: "3.1"

services:
  vidasanadiet_db:
    image: mysql:5.7
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: vidasanadiet_db
      MYSQL_ROOT_USER: uvidasanadiet
      MYSQL_USER: uvidasanadiet
      MYSQL_ROOT_PASSWORD: pasadeuva
      MYSQL_PASSWORD: pasadeuva